# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

variables:
  dockerId: 'LearnDocker'  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: 'LearnDocker'  # Replace with the name of the image you want to publish


steps:
#- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
#- script: docker build -t $(dockerId)/$(imageName) .  # add options to this command to meet your needs
#- script: |
 #   docker build -t $(dockerId).azurecr.io/$(imageName) .
  #  docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
   # docker push $(dockerId).azurecr.io/$(imageName)
   
   #- script: |
    #docker-compose -f docs/docker-compose.yml --project-directory . -p docs up -d
    #docker wait docs_sut_1
    #docker-compose -f docs/docker-compose.yml --project-directory . down
    
 #env:
  #  pswd: $(dockerPassword) 
